# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and Deploy Website to Azure

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.300'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}
          include-prerelease: true

      - name: Build Website
        run: dotnet build ./src/Website/Website.csproj --configuration Release

      - name: Publish Website
        run: dotnet publish ./src/Website/Website.csproj -c Release -o ${{env.DOTNET_ROOT}}/website

      - name: Upload Website for Deployment
        uses: actions/upload-artifact@v2
        with:
          name: .website
          path: ${{env.DOTNET_ROOT}}/website

  deploy-qa:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'QA'
      url: ${{steps.deploy-to-webapp.outputs.webapp-url}}

    steps:
      - name: Download Website
        uses: actions/download-artifact@v2
        with:
          name: .website

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'communities-qa'
          slot-name: 'Production'
          publish-profile: ${{secrets.AZURE_WEBAPP_PUBLISH_PROFILE}}
          package: .
