name: Trigger Build for Pull Request

on:
  pull_request:
    branches:
      - dev
      - qa
      - uat
      - prod
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.300'

jobs:
  build-and-publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@master

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      # Run dotnet build and publish
      - name: Build Solution
        run: dotnet build ./src/Website/Website.csproj --configuration Release
