name: Trigger Build for Pull Requests

on:
  pull_request:
    branches:
      - dev
      - qa
      - uat
      - prod
  workflow_dispatch:

env:
  DOTNET_VERSION: '6.0.300'

jobs:
  build-and-publish:
    name: PR Build
    runs-on: ubuntu-latest
    steps:

      # Checkout the repository
      - name: Checkout
        uses: actions/checkout@master

      # Setup .NET SDK
      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{env.DOTNET_VERSION}}

      # Run dotnet build
      - name: Build Website
        run: dotnet build ./src/Website/Website.csproj --configuration Release
